# Generated by Django 4.1.7 on 2023-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_multipleimage_options_alter_products_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multipleimage",
            name="images",
            field=models.CharField(max_length=2083),
        ),
    ]
