# Generated by Django 4.1.7 on 2023-03-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_products_filterfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="filterField",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                max_length=10,
                null=True,
            ),
        ),
    ]
