# Generated by Django 4.1.7 on 2023-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_products_filterfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
