# Generated by Django 4.1.7 on 2023-03-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_products_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="images",
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
