# Generated by Django 4.1.7 on 2023-03-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_products_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="images",
            new_name="image",
        ),
    ]
