# Generated by Django 4.1.7 on 2023-03-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_rename_images_products_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="image",
            new_name="imgField",
        ),
    ]
