# Generated by Django 4.1.7 on 2023-03-08 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0011_wishcart"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WishCart",
            new_name="WishList",
        ),
        migrations.CreateModel(
            name="WishListItems",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.products",
                    ),
                ),
                (
                    "wishList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wish_list_items",
                        to="base.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wish List Item",
            },
        ),
    ]
