# Generated by Django 4.1.7 on 2023-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_additionaluserinfo_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionaluserinfo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
