# Generated by Django 4.1.7 on 2023-03-11 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_additionaluserinfo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("timeLeft", models.DateTimeField()),
                ("offerDescription", models.CharField(max_length=1500)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.products"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Offer",
            },
        ),
    ]
