# Generated by Django 4.1.7 on 2023-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_specialoffer_timeleft"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
