# Generated by Django 4.1.7 on 2023-03-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_products_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="forDisplay",
            field=models.BooleanField(default=False),
        ),
    ]
