# Generated by Django 4.1.7 on 2023-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_coupon_cart_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="related_products",
            field=models.ManyToManyField(blank=True, to="base.products"),
        ),
    ]
