# Generated by Django 4.1.7 on 2023-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_products_related_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
