# Generated by Django 4.1.7 on 2023-03-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_products_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneDayOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("end_time", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.products"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "One Day Offer",
            },
        ),
    ]
