# Generated by Django 4.1.7 on 2023-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_alter_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
