# Generated by Django 4.1.7 on 2023-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0035_alter_products_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
