# Generated by Django 4.1.7 on 2023-03-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0038_alter_products_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
