# Generated by Django 4.1.7 on 2023-03-19 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_cartitems_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorExtras',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=100)),
                ('hexCode', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'colorExtras',
            },
        ),
        migrations.CreateModel(
            name='sizeExtras',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'sizeExtras',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='colorExtras',
            field=models.ManyToManyField(to='base.colorextras'),
        ),
        migrations.AddField(
            model_name='products',
            name='sizeExtras',
            field=models.ManyToManyField(to='base.sizeextras'),
        ),
    ]
