# Generated by Django 4.1.7 on 2023-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_colorextras_sizeextras_products_colorextras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colorextras',
            name='hexCode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='colorExtras',
            field=models.ManyToManyField(blank=True, to='base.colorextras'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sizeExtras',
            field=models.ManyToManyField(blank=True, to='base.sizeextras'),
        ),
    ]
