# Generated by Django 4.1.7 on 2023-03-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0042_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(),
        ),
    ]
